### ISSUE TITLE
egg file doesn't seems to be install properly without the option -e

### ISSUE THREAD

**Issue by tarrade** [SohierDane/BigQuery_Helper#13]
Hi Sophier,

I am trying to install `BigQuery_Help` in a `conda env`:

```
channels:
- conda-forge
- defaults
dependencies:
- tensorflow
- pip:
  - pip==18.0
  - "git+https://github.com/SohierDane/BigQuery_Helper.git#egg=bq_helper"
```

the issue is that the package doesn't seems to be build properly and only the following file is present:
`/xxx/anaconda/envs/test_joblib/lib/python3.6/site-packages/bq_helper-0.4.1.dist-info`

while a directory called "bq_helper" should be present as well but is not.

there is no info during the installation:
```
Building wheels for collected packages: bq-helper
  Running setup.py bdist_wheel for bq-helper ... done
  Stored in directory: /private/var/folders/l7/00kxfwvs0vbbqxtrp3rpf3yh0000gn/T/pip-ephem-wheel-cache-v1xxogi_/wheels/a4/fa/7e/e5e1cd3750a33698289f7f0c9ad24ed1f16aa5514fe57a33b5
Successfully built bq-helper
```

If I use `git install -e`, it woks but because it install the file in a `scr` folder locally, this will conflict with my local code.

Any idea what need to be fixed ? I created to package using  `"setuptools"` and I never saw this issue. the only difference is that my code is in some folder.

Thanks 
Cheers
Fabien

**Comment by tarrade** [comment]
This package doesn't seems to be maintained anymore. Closing and moving to other tools.

**Comment by hyzhak** [comment]
@tarrade which tool do you recommend instead?
