### ISSUE TITLE
SyntaxError in Mac

### ISSUE THREAD

**Issue by luiceur** [SohierDane/BigQuery_Helper#3]
```
import bq_helper as bq
  File "/Users/lcebaman/src/bq-helper/bq_helper.py", line 92
    print(f"Query cancelled; estimated size of {query_size} exceeds limit of {max_gb_scanned} GB")
                                                                                                ^
SyntaxError: invalid syntax
```

**Comment by SohierDane** [comment]
Does that line actually trigger an error when you run it? Or is this the report from your linter? I saw Flake8 flag the same line, but it looked like it was incorrectly reporting a 'line > 79 characters' style violation as a syntax error.

**Comment by luiceur** [comment]
I think it is an actual error since it does not import the package.
```
In [8]: from bq_helper import BigQueryHelper
   ...:
  File "/Users/lcebaman/src/bq-helper/bq_helper.py", line 92
    print(f"Query cancelled; estimated size of {query_size} exceeds limit of {max_gb_scanned} GB")
                                                                                                ^
SyntaxError: invalid syntax
In [9]: bq_assistant = BigQueryHelper('bigquery-public-data', 'openaq')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-9-35105d4a5155> in <module>()
----> 1 bq_assistant = BigQueryHelper('bigquery-public-data', 'openaq')

NameError: name 'BigQueryHelper' is not defined
In [10]:
```

**Comment by luiceur** [comment]
Getting rid of the print statement seems to fix the problem

**Comment by SohierDane** [comment]
Thanks, I'll take a closer look.

**Comment by SohierDane** [comment]
I'm not able to replicate on any of 3 separate machines, but I did see the same syntax flag from flake8 on my home machine. Was still able to import and run everything fine there. 

Can you try running the `squash_print_bug` branch to see if that fixes the issue? All I did was restructure the print statement to use `str.format` instead of an f string, but `str.format` should be more backwards compatible and so less likely to hit edge cases.

**Comment by SohierDane** [comment]
Also, what version of Python are you running? The f string approach will only work on 3.6+.

**Comment by luiceur** [comment]
Ah! Python 2.7.13

**Comment by SohierDane** [comment]
Phew! I'll go ahead and close this out then. Unfortunately, I can't commit to supporting Python 2.
