### ISSUE TITLE
how should i set credentials?

### ISSUE THREAD

**Issue by cryptid11** [SohierDane/BigQuery_Helper#7]
DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.

I will like something that should speed up the process of using something else to actually explain what's needed to truly makes this happens! :D

**Comment by SohierDane** [comment]
Sorry, I can't provide support for Google's authentication process.

**Comment by cryptid11** [comment]
Are you kidding me? I just want to know how to set up my key, is this so crazy?

**Comment by SohierDane** [comment]
A) The authentication process isn't something I've contributed to at all; don't have any expertise about the authentication process beyond having done it exactly once myself.
B) It's not clear that you've actually read the instructions that the error message provides, what your system configuration is, or what you've already tried to do to resolve the matter. In other words, your comment doesn't meet stackoverflow standards for a minimally viable question, which I feel are reasonable criteria.
